name: iOS IPA Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Clonar proyecto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Angular
        run: npx ng build --configuration production

      - name: Instalar Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Sincronizar iOS
        run: npx cap sync ios

      - name: Instalar CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod install

      - name: Compilar iOS
        run: |
          xcodebuild \
          -workspace ios/App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -archivePath ios/App/App.xcarchive \
          archive \
          CODE_SIGNING_ALLOWED=NO

      - name: Exportar IPA
        run: |
          mkdir Payload
          cp -R ios/App/App.xcarchive/Products/Applications/App.app Payload
          zip -r App.ipa Payload

      - name: Subir IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: App.ipa
